language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

sudo: false

before_script:
  - wget https://www.vlfeat.org/matconvnet/models/imagenet-vgg-verydeep-19.mat

script:
  - python neural_style.py --content examples/1-content.jpg --styles examples/1-style.jpg --output test-$(date +%s).png --iterations 2
